version: '3'
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
      - CLI_ARGS= #optional
    volumes:
      - /etc/docker/duplicati/config:/config
      - /etc/docker:/source
    ports:
      - 8200:8200
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /etc/docker/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9443:9443
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - /etc/docker/mosquitto:/mosquitto
      - /etc/docker/mosquitto/data:/data
      - /etc/docker/mosquitto/log:/log
    ports:
      - 1883:1883
      - 9001:9001

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - /etc/docker/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      # Frontend port
      - 8080:8080
    environment:
      - TZ=Asia/Shanghai
    devices:
      # Make sure this matched your adapter location
      - /dev/ttyUSB2:/dev/ttyACM0